apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lag-app
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`german.packetcraft.dev`)
      services:
        - name: lag-app
          port: 80
